# Plugins
#---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

# Plugin Config
set -g @tmux-gruvbox 'dark'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5' # minutes

# Tmux Core Config
#---
set -g default-terminal "tmux-256color" 
set-option -g default-command bash

set-window-option -g mode-keys vi

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Keybindings
#---
set-option -g prefix M-Space

# update current session's default directory to current path
bind-key M-c attach-session -c "#{pane_current_path}"

# rename current window
unbind-key r
bind-key r command-prompt -I "#W" { rename-window "%%" }

# rename current session
unbind-key R
bind-key R command-prompt { rename-session "%%" }

# create new session
unbind-key S
bind S command-prompt -p "New Session:" "new-session -A -s '%%'"

# kill current session
bind K confirm kill-session

# on session kill, switch to another active session if available
set-option -g detach-on-destroy off

# Navigation, not using prefix
bind-key -n M-, select-window -t:-1
bind-key -n M-. select-window -t:+1

bind-key -n M-< swap-window -t:-1 \; select-window -t:-1
bind-key -n M-> swap-window -t:+1 \; select-window -t:+1

bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R

bind-key -n M-H resize-pane -L
bind-key -n M-J resize-pane -D
bind-key -n M-K resize-pane -U
bind-key -n M-L resize-pane -R

bind-key -n M-[ rotate-window -U
bind-key -n M-] rotate-window -D

# Initialize tmux plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Plugin Overrides:
# tmux-gruvbox dark
set-option -g status-right "#[fg=colour248,nobold,noitalics,nounderscore]#[bg=colour248,fg=colour237] #h "
