include-file = tokyo-night-default.ini

[colors]
background       = ${theme.bg}
foreground       = ${theme.fg}
attention-high   = ${theme.bright1}
attention-medium = ${theme.bright3}
attention-low    = ${theme.bright5}

[settings]
screenchange-reload = true
pseudo-transparency = true

[bar/primary]
monitor = ${env:MONITOR:}

width = 100%
height = 24pt
radius = 0

background = ${colors.background}
foreground = ${colors.foreground}
line-size = 3pt
border-size = 0pt

font-0 = FiraCode Nerd Font

module-margin = 1
modules-left = xworkspaces
modules-center = i3
modules-right = wlan pulseaudio battery date

cursor-click = pointer
cursor-scroll = ns-resize

; tray-position = none
[module/tray]
position = none

[module/pulseaudio]
type = internal/pulseaudio

; Non-muted volume display settings
format-volume-prefix = "  "
format-volume = <label-volume>
label-volume = %percentage%%

; Muted volume display settings
format-muted-prefix = "  "
format-muted-foreground = ${colors.attention-medium}
label-muted = muted

[module/battery]
type = internal/battery

; Use the following command to list batteries and adapters:
; `ls -1 /sys/class/power_supply/`
battery = BAT1
adapter = ACAD

; Discharging configuration
ramp-capacity-0 = " "
ramp-capacity-1 = " " 
ramp-capacity-2 = " " 
ramp-capacity-3 = " " 
ramp-capacity-4 = " " 
ramp-capacity-0-foreground = ${colors.attention-high}
ramp-capacity-1-foreground = ${colors.attention-medium}
ramp-capacity-2-foreground = ${colors.attention-low}
ramp-capacity-3-foreground = ${colors.foreground}
ramp-capacity-4-foreground = ${colors.foreground}
label-discharging = %percentage%%
format-discharging = <ramp-capacity> <label-discharging>

; Charging configuration
animation-charging-0 = " "
animation-charging-1 = " "
animation-charging-2 = " "
animation-charging-3 = " "
animation-charging-4 = " "
animation-charging-framerate = 750
label-charging = "%percentage%%"
format-charging = <animation-charging> <label-charging>

[module/date]
type = internal/date
interval = 1
date = %A, %D %I:%M%P
label = %date%

[network-base]
type = internal/network
interval = 5

format-connected-prefix = "  "
format-connected = <label-connected>

format-disconnected-prefix = "  "
format-disconnected = <label-disconnected>
format-disconnected-foreground = ${colors.attention-high}
label-disconnected = disconnected

[module/wlan]
inherit = network-base
interface-type = wireless

label-connected = %essid%

[module/xworkspaces]
type = internal/xworkspaces
pin-workspaces = true

label-active-underline= ${colors.attention-medium}
label-active = %name%
label-active-padding = 1

label-urgent-background = ${colors.attention-high}
label-urgent = %name%
label-urgent-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-empty = %name%
label-empty-padding = 1


[module/i3]
type = internal/i3
pin-workspaces = true

; configure how i3 modes are displayed. For example 'resize' mode.
label-mode-background = ${colors.attention-high}
label-mode = %mode%
label-mode-padding = 4

format = <label-mode>
